name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@2.0.0
      env:
        SLUG: ah-jwt-auth
