name: PR Checks
permissions:
  contents: read

on: pull_request

jobs:
  lint:
    name: WPCS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: WPCS check
        uses: 10up/wpcs-action@39f1a9eb6139795e6798d11b51eeecf5a9678ccc # v2.1.0
        with:
          standard: 'WordPress'
          excludes: tests
          enable_warnings: true
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Run tests
        run: composer test
