name: Release tasks
permissions:
  actions: read
  contents: write
  id-token: write
  attestations: write
  artifact-metadata: write

on:
  release:
    types: [ published ]

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610 # v0.24.0
        with:
          output-file: sbom.spdx.json
          dependency-snapshot: true
      - uses: actions/attest@v4
        with:
          subject-path: sbom.spdx.json
          sbom-path: sbom.spdx.json
