name: Release tasks
permissions:
  actions: read
  contents: write
  id-token: write
  attestations: write
  artifact-metadata: write

on:
  release:
    types: [ published ]

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: anchore/sbom-action@aa80c8c5bd439a416a62804f2151ab38c671a638 # v0.24.1
        with:
          output-file: sbom.spdx.json
          dependency-snapshot: true
      - uses: actions/attest@1e69f48acb82d1966a394da916b4c1698aa569d6 # v4.2.2
        with:
          subject-path: sbom.spdx.json
          sbom-path: sbom.spdx.json
